package planner

import (
	"context"
	"fmt"

	"github.com/futurematic/kernel/internal/domain"
	"github.com/futurematic/kernel/internal/store"
)

// Planner expands intents into atomic changes and computes deterministic hashes
type Planner interface {
	// Plan expands intents into changes, evaluates policy, and computes a deterministic hash
	Plan(ctx context.Context, req PlanRequest) (*domain.Plan, error)
}

// PlanRequest contains the inputs for planning
type PlanRequest struct {
	ActorID     string
	NamespaceID *string
	AsOf        domain.AsOf
	Intents     []domain.Intent
}

// NewPlanner creates a new planner
func NewPlanner(store store.Store, expander *Expander, hasher *Hasher) Planner {
	return &planner{
		store:    store,
		expander: expander,
		hasher:   hasher,
	}
}

type planner struct {
	store    store.Store
	expander *Expander
	hasher   *Hasher
}

// Plan implements the Planner interface
func (p *planner) Plan(ctx context.Context, req PlanRequest) (*domain.Plan, error) {
	// Resolve asof to seq
	asofSeq, err := p.store.ResolveAsOf(ctx, req.AsOf)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve asof: %w", err)
	}

	// Expand intents to changes
	expanded, err := p.expander.Expand(ctx, req.Intents, req.NamespaceID, asofSeq, p.store)
	if err != nil {
		return nil, fmt.Errorf("failed to expand intents: %w", err)
	}

	// Get active policy set for namespace (if any)
	var policyHash string
	if req.NamespaceID != nil {
		policySet, err := p.store.GetActivePolicySet(ctx, *req.NamespaceID)
		if err != nil {
			return nil, fmt.Errorf("failed to get policy set: %w", err)
		}
		if policySet != nil {
			policyHash = policySet.PolicyHash
		}
	}

	// Compute plan hash (deterministic)
	planHash, err := p.hasher.HashPlan(req.NamespaceID, req.Intents, expanded, policyHash)
	if err != nil {
		return nil, fmt.Errorf("failed to hash plan: %w", err)
	}

	// Create plan (policy evaluation will be done by policy engine, not here)
	plan := &domain.Plan{
		ID:          "", // Will be generated by caller
		CreatedAt:   domain.Now(), // Will be set by caller
		ActorID:     req.ActorID,
		NamespaceID:  req.NamespaceID,
		AsOfSeq:     &asofSeq,
		Intents:     req.Intents,
		Expanded:    expanded,
		Class:       1, // Default class
		PolicyReport: domain.PolicyReport{}, // Will be populated by policy engine
		Hash:        planHash,
	}

	return plan, nil
}
