name: Feature request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the feature and why it would help.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature
      placeholder: "e.g. Add a config option to ..."
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: Detail
      description: Use cases, possible implementation, alternatives
      placeholder: "Describe the behaviour you want and how you'd use it."
    validations:
      required: false
